# Generated by Django 5.2.6 on 2025-09-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('gu', 'Gujarati')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='standard',
            field=models.CharField(blank=True, choices=[('8th', 'Standard 8'), ('9th', 'Standard 9'), ('10th', 'Standard 10')], max_length=4, null=True),
        ),
    ]
