// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/language": {
    params: {};
  };
  "/standards": {
    params: {};
  };
  "/subjects": {
    params: {};
  };
  "/chapters/:subjectId": {
    params: {
      "subjectId": string;
    };
  };
  "/subject/test/:chapterId": {
    params: {
      "chapterId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-up" | "/language" | "/standards" | "/subjects" | "/chapters/:subjectId" | "/subject/test/:chapterId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/sign-up.tsx": {
    id: "routes/sign-up";
    page: "/sign-up";
  };
  "routes/language.tsx": {
    id: "routes/language";
    page: "/language";
  };
  "routes/standards.tsx": {
    id: "routes/standards";
    page: "/standards";
  };
  "routes/subjects.tsx": {
    id: "routes/subjects";
    page: "/subjects";
  };
  "routes/chapters.$subjectId.tsx": {
    id: "routes/chapters.$subjectId";
    page: "/chapters/:subjectId";
  };
  "routes/test.$chapterId.tsx": {
    id: "routes/test.$chapterId";
    page: "/subject/test/:chapterId";
  };
};